markdown: rdiscount
permalink: /:title
rdiscount extensions: [smart]
exclude: [ .gitignore, README.md, Gemfile, Gemfile.lock, Procfile, vendor, Rakefile, the_app.rb, elasticsearch, app, tmp, log ]
elasticsearch_host: 127.0.0.1:9200 # this is where elasticsearch is running
category_dir: /categories
exclude_from_search: 'no_index'

# let's embed some video you guys!
wistia_embed_settings:
  playerColor: "40aaef" # $accent_blue from screen.sass
  videoWidth: "730"
  playButton: true
  embedType: "async"
  controlsVisibleOnLoad: false
